[project]
name = "vibe"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Udo Klarhöfer", email = "klarhoefer@gmail.com" }
]
requires-python = ">=3.12"
dependencies = []

[project.scripts]
vibe = "vibe:main"

[build-system]
requires = ["uv_build>=0.12.13,<0.13.0"]
build-backend = "uv_build"
